In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
np.random.seed(0)
z = np.random.randn(9, 2)
z

np.random.seed(0)
y = np.random.randint(2, size=9)

y

np.random.seed(5)
nokta = np.random.randn(1, 2)
nokta

array([[ 0.44122749, -0.33087015]])

In [4]:
z

array([[ 1.76405235,  0.40015721],
       [ 0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826]])

In [10]:
zdf=pd.DataFrame(z)

In [16]:
zdf["distance"]=np.sqrt(((z-nokta)**2).mean())

In [21]:
np.sqrt(((z-nokta)**2).sum(axis=1))

array([1.51137904, 2.62733406, 1.56596988, 0.53959646, 0.91988998,
       1.80971162, 0.55414413, 0.66454971, 1.06033011])

In [22]:
zdf["distance"]=np.sqrt(((z-nokta)**2).sum(axis=1))

In [24]:
zdf["y"]=y

In [25]:
zdf

0         1  distance  y
0  1.764052  0.400157  1.511379  0
1  0.978738  2.240893  2.627334  1
2  1.867558 -0.977278  1.565970  1
3  0.950088 -0.151357  0.539596  0
4 -0.103219  0.410599  0.919890  1
5  0.144044  1.454274  1.809712  1
6  0.761038  0.121675  0.554144  1
7  0.443863  0.333674  0.664550  1
8  1.494079 -0.205158  1.060330  1

In [44]:
int((zdf.sort_values("distance")["y"].head(k)).mean()>0.5)

1

In [49]:
def knn(z, y, nokta, k): # classification
    zdf=pd.DataFrame(z)
    zdf["distance"]=np.sqrt(((z-nokta)**2).sum(axis=1))
    zdf["y"]=y
    return int((zdf.sort_values("distance")["y"].head(k)).mean()>0.5)

In [55]:
knn(z,y,nokta,3)

1

In [57]:
def knn_reg(z, y, nokta, k): # regression
    zdf=pd.DataFrame(z)
    zdf["distance"]=np.sqrt(((z-nokta)**2).sum(axis=1))
    zdf["y"]=y
    return zdf.sort_values("distance")["y"].head(k).mean()

In [60]:
np.random.seed(0)
X = np.random.randn(20, 2)
y = np.random.randn(20)
nokta = np.random.randn(1, 2)

In [61]:
knn_reg(X,y,nokta,3)

-0.4136338174565896